### ISSUE TITLE
About Warning on BackupCatalog at bareos-fd

### ISSUE THREAD

**Issue by opelx** [barcus/bareos#65]
Hi,

I'm using the docker ubuntu postgresql compose file. I get a warning:

        buildkitsandbox-fd JobId 4: Could not stat "/var/lib/bareos/bareos.sql": ERR=No such file or directory
        buildkitsandbox-fd JobId 4: Cannot open "/etc/bareos/.rndpwd": ERR=Permission denied.

on 'bareos-fd' backup job. Jumping into the container shows:

        $ sudo docker-compose exec bareos-fd bash
        Password: 
        root@de248682369a:/# ls -la /etc/bareos/.rndpwd
        -r-------- 1 root root 522 Mar 13 22:54 /etc/bareos/.rndpwd
        root@de248682369a:/# ls -la /var/lib/bareos/          
        bareos-fd.9102.pid    bareos-fd.9102.state  storage/              
        root@de248682369a:/# ls -la /var/lib/bareos/
        total 24
        drwxr-xr-x 1 bareos bareos 4096 Apr 24 21:10 .
        drwxr-xr-x 1 root   root   4096 Apr 24 20:36 ..
        -rw-r----- 1 bareos root      2 Apr 24 20:36 bareos-fd.9102.pid
        -rw-r--r-- 1 bareos root    596 Apr 24 21:10 bareos-fd.9102.state
        drwxr-xr-x 2 root   root   4096 Feb 11 18:10 storage

The warning is irritating and should be fixed. I haven't seen this on real host backup yet (no BackupCatalog on this host yet).

Edit, I can confirm this will also happend on real machine (manually started the job):

        nuc-fd JobId 5: Could not stat "/var/lib/bareos/bareos.sql": ERR=Datei oder Verzeichnis nicht gefunden
        [me@nuc ~]$ sudo ls -la /var/lib/bareos/
        insgesamt 16
        drwxrwx---.  2 bareos bareos 4096 24. Apr 21:57 .
        drwxr-xr-x. 74 root   root   4096 25. Jul 2019  ..
        -rw-r-----.  1 root   bareos    6 24. Apr 14:41 bareos-fd.9102.pid
        -rw-r-----.  1 root   bareos 2196 24. Apr 21:57 bareos-fd.9102.state

BTW, shouldn't it be on  /var/lib/bareos/scripts/ ?

**Comment by barcus** [comment]
Hey ! 
First of all, i have never used pgsql version and i think people don't take care about their own catalog backup.

I think it's the same issue than Ubuntu version about bareos.sql file.
Just to let you know this file is generated by the director during catalog backup with a perl script (at least for ubuntu with bareos v19 pgsql) : 

`/usr/lib/bareos/scripts/make_catalog_backup.pl MyCatalog`

This script generate bareos.sql inside director container.
I added something special in docker-compose files in order to allow client (file daemon) container to access it but i think something is missing again.
Also i have just discovered there is an issue in docker-compose file for ubuntu-pgsql, 3306 is MySQL port :)

I'm gonna check that soon. Could be great if it works out of the box even for PG version !

**Comment by barcus** [comment]
oh i found it :p

**Comment by opelx** [comment]
Hi

> First of all, i have never used pgsql version.

Ok, following [Decide about the Database Backend](https://docs.bareos.org/IntroductionAndTutorial/InstallingBareos.html#decide-about-the-database-backend) :

- MariaDB/MySQL  Deprecated since version 19.0.0.
- PostgreSQL This is the preferred default database backend. ...  this is your choice!

Since it's a new installation (to replace bacula) I choosed pgsl...

Anway, can you update the docker images from git master please?

        $ sudo docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.CreatedAt}}\t{{.Size}}" | grep bareos
        barcus/bareos-director                   19-ubuntu-pgsql     1d555f730649        2020-04-25 00:21:21 +0200 CEST   134MB
        barcus/bareos-webui                      19-ubuntu           7bfdd72bfac7        2020-03-13 22:54:19 +0100 CET    206MB
        barcus/bareos-client                     19-ubuntu           c07c4fc5794c        2020-03-13 22:54:11 +0100 CET    155MB
        barcus/bareos-storage                    19-ubuntu           bb019598bf95        2020-03-13 22:54:01 +0100 CET    92.5MB

**Comment by barcus** [comment]
Hi,
Images are automaticaly built from Github CI on each commit to master.
Did you try a `docker pull barcus/bareos-director:19-ubuntu-pgsql` ?

**Comment by opelx** [comment]
Hi,
are you sure that's true for all hooks?
Following [barcus/bareos-client](https://hub.docker.com/r/barcus/bareos-client) -> By barcus • Updated a month ago
but [barcus/bareos-director](https://hub.docker.com/r/barcus/bareos-director) -> By barcus • Updated 3 days ago

Maybe I'm wrong, run never before in such issue, stop/start the compose always pulled the latest ...

**Comment by barcus** [comment]
Hi
Yes i'm sure :)
There was only an issue on director container.
You have to remove the control file which is generated by the director container in order to apply your docker-compose settings again (/etc/bareos/bareos-config.control)

Maybe i have to update the readme about those files for people who are not comfortable with docker workflow !
